### ISSUE TITLE
Multi-param validation & filtering

### ISSUE THREAD

**Issue by rpkilby** [rpkilby/django-filter#12]
@carltongibson - just jotting down some preliminary thoughts. Do you have any feedback?

----

**Context:**

Users periodically request how to validate and filter against multiple params. The goto advice has been to implement something based on `MultiWidget`, however there are three main deficiencies in my mind:

- It's verbose, users will typically need to subclass `MultiWidget`, `MultiValueField`, and `Filter`.
- It's difficult to implement. For new Django users, the `MultiWidget`/`MultiValueField` API is somewhat confusing (maybe I just didn't grok it for some reason, but I remember struggling with it in the past)
- As mentioned elsewhere, validation errors don't account for sub-widgets and are raised under the unsuffixed parameter name. This is acceptable for forms usage, where all sub widgets and errors are rendered together, but this mismatch doesn't work in an API context. 

**Proposal:**

Add new API surface around multi-param filtering. This consists of two things:
- A `Meta.multi` or `Meta.multiple` option that maps group labels (?) to a list of filter names.
- Handling of `validate_multi_*` and `filter_multi_*`, which correspond to the `multi` labels.

In practice this would look like:

```python
class MyFilter(filters.FilterSet):
    field_a = filters.CharFilter(...)
    field_b = filters.CharFilter(...)

    class Meta:
        model = MyModel
        multi = {
            'group_a': ['field_a', 'field_b'],
        }

    def validate_multi_group_a(self, form, *, field_a, field_b):
        if not some_condition(field_a, field_b):
            form.add_error('field_a', '...')
            form.add_error('field_b', '...')

            # Note: not the following, since it halts validation
            raise ValidationError({'field_a': ['...'], 'field_b': ['...']})

    def filter_multi_group_a(self, qs, *, field_a, field_b):
        return qs.do_a_thing(field_a=field_a, field_b=field_b)
```

The above hooks are purely opt-in.
- If a `validate_multi_<group name>` is defined, it will be called during the validation phase. Note that individual filter validation is still performed, and the validated values are passed to the method.
- If a `filter_multi_<group name>` is defined, it will be called during the filter phase *in lieu* of the individual `.filter()` methods.
- Empty values are passed to these methods, since it's necessary for validation/condition checking.

**Notes:**
- The above should be a relatively simple internal implementation, since the `FilterSet` is just calling hook methods at the appropriate time. One possible complication is validation, which will require adding a `.clean()` method to the form class creation.. it should be fine...
- The above should be simple to implement by users, since they only have to touch the `FilterSet` API, instead of mucking around with forms.
- The above is flexible - users can assert any arbitrary validation rules (e.g., fields must be all present together, they must be exclusive, some fields are required in some cases, etc...).
    - Example for the old `Meta.together` option (require all values are valid/present).
        ```python
        def validate_multi_group_a(self, form, *, field_a, field_b):
            if field_a and not field_b:
                form.add_error('field_b', 'Field A and Field B are required together.')
            elif not field_a and field_b:
                form.add_error('field_a', 'Field A and Field B are required together.')
        ```
    - Example for the rejected `Meta.exclusive` option (see `#784`).
        ```python
        def validate_multi_group_a(self, form, *, field_a, field_b):
            if field_a and field_b:
                form.add_error('field_a', 'Field A and Field B are mutually exclusive.')
                form.add_error('field_b', 'Field A and Field B are mutually exclusive.')
        ```
    - Example for more complex filtering (the `MuliWidget` use case).
        ```python
        def validate_multi_group_a(self, form, *, field_a, field_b):
            """same as above for Meta.together"""

        def filter_multi_group_a(self, qs, *, field_a, field_b):
            return qs.filter(field_a__isnull=field_a, field_b__gte=field_b).
        ```

**Comment by carltongibson** [comment]
OK. Nice. 

Can I ask, How would it look if we had a GroupFilter class that took Filters and allowed implementing filter() plus validate()?

I.e. just pulling what you have here into a composed class, rather than having the API directly on FilterSet.

**Comment by rpkilby** [comment]
That was actually my first thought - leverage the declarative filters. And I've kind of gone back and forth on both implementations after writing several lengthy paragraphs on the matter. Changed my opinion mid-response.. 😅

At this point, I see two proposals:

1. The one above.
2. The below:
    ```python
    # Note that FilterGroup is not a Filter subclass
    class MyFilterGroup(FilterGroup):
        def filter(self, qs, **params):
            ...
        def validate(self, form, **params):
            ...
    
    class MyFilter(FilterSet):
        field_a = CharFilter(...)
        field_b = CharFilter(...)
        group = MyFilterGroup(
            filters=['field_a', 'field_b'],
        )
    ```

At this point, I'm leaning towards option 2. Option 1 is still attractive in that the code is simple - it's not necessary to write custom classes. That said, there isn't any abstraction for reusability. We could write helper functions, but that's about it. Option 2 would allow us/users to write reusable `FilterGroup`s. Right now, the only thing I don't like about the declarative approach is that they don't make sense as a declared attribute on the `FilterSet`. With `Filter`s, the attribute name is the exposed query param. With `FilterGroup`s, the attribute name is functionless. e.g., a user wouldn't ever include `?group=foo` in their query string. 

Maybe a third option is to mix the styles? Use `FilterGroup`s in the meta options? e.g.,

```python
# Note that FilterGroup is not a Filter subclass
class MyFilter(FilterSet):
    field_a = CharFilter(...)
    field_b = CharFilter(...)
    field_c = CharFilter(...)
    field_d = CharFilter(...)

    class Meta:
        filters = []
    group = MyFilterGroup(
        filters=['field_a', 'field_b'],
    )
```


----

That was actually my first thought - leverage the declarative filters. One of the benefits would be that we could provide a standard set of group filters with standard error messages. e.g., something like


On a technical note, the first example isn't really viable - nesting the filters inside another filter would create all sorts of weird introspectability issues similar to `MultiWidget`. Getting this to work would require coupling the implementation the `FilterSet` to the implementation details of `GroupFilter`, which would be messy. Aside from style (it potentially makes sense to visually nest the grouped filters inside `GroupFilter`?), I don't see any reason to go this route. 

The second approach is more reasonable, linking the filters by parameter name. However, there is still the issue in that `GroupFilter` isn't *really* a filter. As in, a user wouldn't submit `?group=foo` as part of their querystring. Similar to above, the `FilterSet` would need to be aware of `GroupFilter`s, specifically excluding them from 



But in general, I don't think the declarative approach makes sense for group/multi filtering, because there is a conceptual mismatch. A filter typically represents a single filterable field. 

Most importantly, group filtering isn't *really* a `Filter` at a conceptual level. 

The second example could work, however the problem is that `GroupFilter` kind of is and kind of isn't a filter. On the one hand, it does need to perform validation and filtering. On the other, it is itself *not* a filterable entity. e.g., you wouldn't submit `?group=foo` as part of the query string. None of the form field attributes would be relevant, etc... If we were to go this route, it would have to be a separate API that doesn't inherit the base `Filter` class. We also want to call something other than a filter, so as not to create confusion with actual filters.

----

So I really see the second option and the original proposal as having trade offs. On the one hand, the declarative route would give you some customization (e.g., you can name the methods whatever you want). On the other, does it really matter? Who actually cares about having flexibility? The proposed convention of `validate_group_*`/`filter_group_*` is rooted in the same convention as the form `clean_<field>` and serializer `validate_<field>` methods. 

If I had to tl;dr... multi/group filtering doesn't really fit in  the single  and is more a higher order validation/filter function that operates on multiple individual filters. This

**Comment by rpkilby** [comment]
That was actually my first thought - leverage the declarative filters. And I've kind of gone back and forth on both implementations after writing several lengthy paragraphs on the matter. Changed my opinion mid-response.. 😅

At this point, I see two proposals:

1. The one above.
2. The below:
    ```python
    # Note that FilterGroup is not a Filter subclass
    class MyFilterGroup(FilterGroup):
        def filter(self, qs, **params):
            ...
        def validate(self, form, **params):
            ...
    
    class MyFilter(FilterSet):
        field_a = CharFilter(...)
        field_b = CharFilter(...)
        group = MyFilterGroup(
            filters=['field_a', 'field_b'],
        )
    ```

At this point, I'm leaning towards option 2. Option 1 is still attractive in that the code is simple - it's not necessary to write custom classes. That said, there isn't any abstraction for reusability. We could write helper functions, but that's about it. Option 2 would allow us/users to write reusable `FilterGroup`s. Right now, the only thing I don't like about the declarative approach is that they don't make sense as a declared attribute on the `FilterSet`. With `Filter`s, the attribute name is the exposed query param. With `FilterGroup`s, the attribute name is functionless. e.g., a user wouldn't ever include `?group=foo` in their query string. 

Maybe a third option is to mix the styles? Use `FilterGroup`s in the meta options? e.g.,

```python
# Note that FilterGroup is not a Filter subclass
class MyFilter(FilterSet):
    field_a = CharFilter(...)
    field_b = CharFilter(...)
    field_c = CharFilter(...)
    field_d = CharFilter(...)

    class Meta:
        model = MyModel
        fields = ['field_a', 'field_b', 'field_c', 'field_d']
        groups = [
            ExclusiveGroup(filters=['field_a', 'field_b']),
            RequiredGroup(filters=['field_c', 'field_d']),
        ]
```

How does that last option sound?

**Comment by rpkilby** [comment]
@carltongibson - I'm going to go ahead and WIP up that last example.

**Comment by carltongibson** [comment]
OK. I haven't come to a conclusion. (🎯: "Nice API") 👍

**Comment by rpkilby** [comment]
btw, I'm still working on this. I've just caught up on some unrelated Circle CI work, which is now finished. I hope to have this ready either this weekend or the next.

**Comment by rpkilby** [comment]
ach, I'm eventually going to finish this up. It's just taken a back seat to some work on DRF and djangorestframework-filters (still trying to get 1.0 out the door... _it's only been 3+ years in the making!_). Also, the PR should maybe address iss 1020.

**Comment by rpkilby** [comment]
Took me a year, but it's just about ready lol.
